name: diffae
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  # TVM:
  - decorator
  - attrs
  - cython
  - llvmdev
  - tornado
  - psutil
  - xgboost
  - cloudpickle
  - pytest
  - pip:
    - whl/torch-1.13.0a0+gitae57bd1-cp38-cp38-macosx_12_0_arm64.whl
    - whl/onnx-1.12.0-cp38-cp38-macosx_12_0_arm64.whl
    - whl/tvm-0.9.0-cp38-cp38-macosx_12_0_arm64.whl
    - pytorch-lightning
    - torchvision
    - onnxruntime
    - imgui[glfw]==1.4
    - pytorch-fid
    - lpips
    - lmdb
    - gdown
    - pandas

# conda env update -f environment_mac.yml --prune
