name: diffae
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch-lightning=1.6
  - pytorch=1.12
  - cudatoolkit=11.3
  - torchvision=0.13
  - scipy=1.6
  - numpy=1.22
  - tqdm
  - pandas=1.4
  - ftfy
  - regex
  - gdown
  - cachetools
  - pip
  - pip:
    - imgui[glfw]==1.4
    - pytorch-fid
    - lpips
    - lmdb

# conda env update -f environment.yml --prune
